/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PilotsRouteImport } from './routes/pilots'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CognitesRouteImport } from './routes/cognites'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsShunyaiRouteImport } from './routes/products.shunyai'
import { Route as ProductsNyaynetraRouteImport } from './routes/products.nyaynetra'
import { Route as ProductsIkshanaRouteImport } from './routes/products.ikshana'
import { Route as ProductsHealthHubRouteImport } from './routes/products.health-hub'
import { Route as ProductsExternovateRouteImport } from './routes/products.externovate'
import { Route as ProductsCwosRouteImport } from './routes/products.cwos'
import { Route as ProductsCogniDocRouteImport } from './routes/products.cogni-doc'
import { Route as ProductsCobotsRouteImport } from './routes/products.cobots'
import { Route as ProductsChaxuRouteImport } from './routes/products.chaxu'
import { Route as ProductsBlisstrailRouteImport } from './routes/products.blisstrail'
import { Route as ProductsAwcsRouteImport } from './routes/products.awcs'
import { Route as ProductsAskcogniRouteImport } from './routes/products.askcogni'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as CognitesMycogniRouteImport } from './routes/cognites.mycogni'
import { Route as CognitesLoginRouteImport } from './routes/cognites.login'

const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotsRoute = PilotsRouteImport.update({
  id: '/pilots',
  path: '/pilots',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CognitesRoute = CognitesRouteImport.update({
  id: '/cognites',
  path: '/cognites',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsShunyaiRoute = ProductsShunyaiRouteImport.update({
  id: '/shunyai',
  path: '/shunyai',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsNyaynetraRoute = ProductsNyaynetraRouteImport.update({
  id: '/nyaynetra',
  path: '/nyaynetra',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsIkshanaRoute = ProductsIkshanaRouteImport.update({
  id: '/ikshana',
  path: '/ikshana',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsHealthHubRoute = ProductsHealthHubRouteImport.update({
  id: '/health-hub',
  path: '/health-hub',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsExternovateRoute = ProductsExternovateRouteImport.update({
  id: '/externovate',
  path: '/externovate',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsCwosRoute = ProductsCwosRouteImport.update({
  id: '/cwos',
  path: '/cwos',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsCogniDocRoute = ProductsCogniDocRouteImport.update({
  id: '/cogni-doc',
  path: '/cogni-doc',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsCobotsRoute = ProductsCobotsRouteImport.update({
  id: '/cobots',
  path: '/cobots',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsChaxuRoute = ProductsChaxuRouteImport.update({
  id: '/chaxu',
  path: '/chaxu',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsBlisstrailRoute = ProductsBlisstrailRouteImport.update({
  id: '/blisstrail',
  path: '/blisstrail',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsAwcsRoute = ProductsAwcsRouteImport.update({
  id: '/awcs',
  path: '/awcs',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsAskcogniRoute = ProductsAskcogniRouteImport.update({
  id: '/askcogni',
  path: '/askcogni',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const CognitesMycogniRoute = CognitesMycogniRouteImport.update({
  id: '/mycogni',
  path: '/mycogni',
  getParentRoute: () => CognitesRoute,
} as any)
const CognitesLoginRoute = CognitesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CognitesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/blog': typeof BlogRoute
  '/cognites': typeof CognitesRouteWithChildren
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/enterprise': typeof EnterpriseRoute
  '/pilots': typeof PilotsRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRouteWithChildren
  '/research': typeof ResearchRoute
  '/cognites/login': typeof CognitesLoginRoute
  '/cognites/mycogni': typeof CognitesMycogniRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/askcogni': typeof ProductsAskcogniRoute
  '/products/awcs': typeof ProductsAwcsRoute
  '/products/blisstrail': typeof ProductsBlisstrailRoute
  '/products/chaxu': typeof ProductsChaxuRoute
  '/products/cobots': typeof ProductsCobotsRoute
  '/products/cogni-doc': typeof ProductsCogniDocRoute
  '/products/cwos': typeof ProductsCwosRoute
  '/products/externovate': typeof ProductsExternovateRoute
  '/products/health-hub': typeof ProductsHealthHubRoute
  '/products/ikshana': typeof ProductsIkshanaRoute
  '/products/nyaynetra': typeof ProductsNyaynetraRoute
  '/products/shunyai': typeof ProductsShunyaiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/blog': typeof BlogRoute
  '/cognites': typeof CognitesRouteWithChildren
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/enterprise': typeof EnterpriseRoute
  '/pilots': typeof PilotsRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRouteWithChildren
  '/research': typeof ResearchRoute
  '/cognites/login': typeof CognitesLoginRoute
  '/cognites/mycogni': typeof CognitesMycogniRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/askcogni': typeof ProductsAskcogniRoute
  '/products/awcs': typeof ProductsAwcsRoute
  '/products/blisstrail': typeof ProductsBlisstrailRoute
  '/products/chaxu': typeof ProductsChaxuRoute
  '/products/cobots': typeof ProductsCobotsRoute
  '/products/cogni-doc': typeof ProductsCogniDocRoute
  '/products/cwos': typeof ProductsCwosRoute
  '/products/externovate': typeof ProductsExternovateRoute
  '/products/health-hub': typeof ProductsHealthHubRoute
  '/products/ikshana': typeof ProductsIkshanaRoute
  '/products/nyaynetra': typeof ProductsNyaynetraRoute
  '/products/shunyai': typeof ProductsShunyaiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/blog': typeof BlogRoute
  '/cognites': typeof CognitesRouteWithChildren
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/enterprise': typeof EnterpriseRoute
  '/pilots': typeof PilotsRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRouteWithChildren
  '/research': typeof ResearchRoute
  '/cognites/login': typeof CognitesLoginRoute
  '/cognites/mycogni': typeof CognitesMycogniRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/askcogni': typeof ProductsAskcogniRoute
  '/products/awcs': typeof ProductsAwcsRoute
  '/products/blisstrail': typeof ProductsBlisstrailRoute
  '/products/chaxu': typeof ProductsChaxuRoute
  '/products/cobots': typeof ProductsCobotsRoute
  '/products/cogni-doc': typeof ProductsCogniDocRoute
  '/products/cwos': typeof ProductsCwosRoute
  '/products/externovate': typeof ProductsExternovateRoute
  '/products/health-hub': typeof ProductsHealthHubRoute
  '/products/ikshana': typeof ProductsIkshanaRoute
  '/products/nyaynetra': typeof ProductsNyaynetraRoute
  '/products/shunyai': typeof ProductsShunyaiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/applications'
    | '/blog'
    | '/cognites'
    | '/contact'
    | '/developers'
    | '/enterprise'
    | '/pilots'
    | '/platform'
    | '/pricing'
    | '/products'
    | '/research'
    | '/cognites/login'
    | '/cognites/mycogni'
    | '/products/$slug'
    | '/products/askcogni'
    | '/products/awcs'
    | '/products/blisstrail'
    | '/products/chaxu'
    | '/products/cobots'
    | '/products/cogni-doc'
    | '/products/cwos'
    | '/products/externovate'
    | '/products/health-hub'
    | '/products/ikshana'
    | '/products/nyaynetra'
    | '/products/shunyai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/applications'
    | '/blog'
    | '/cognites'
    | '/contact'
    | '/developers'
    | '/enterprise'
    | '/pilots'
    | '/platform'
    | '/pricing'
    | '/products'
    | '/research'
    | '/cognites/login'
    | '/cognites/mycogni'
    | '/products/$slug'
    | '/products/askcogni'
    | '/products/awcs'
    | '/products/blisstrail'
    | '/products/chaxu'
    | '/products/cobots'
    | '/products/cogni-doc'
    | '/products/cwos'
    | '/products/externovate'
    | '/products/health-hub'
    | '/products/ikshana'
    | '/products/nyaynetra'
    | '/products/shunyai'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/applications'
    | '/blog'
    | '/cognites'
    | '/contact'
    | '/developers'
    | '/enterprise'
    | '/pilots'
    | '/platform'
    | '/pricing'
    | '/products'
    | '/research'
    | '/cognites/login'
    | '/cognites/mycogni'
    | '/products/$slug'
    | '/products/askcogni'
    | '/products/awcs'
    | '/products/blisstrail'
    | '/products/chaxu'
    | '/products/cobots'
    | '/products/cogni-doc'
    | '/products/cwos'
    | '/products/externovate'
    | '/products/health-hub'
    | '/products/ikshana'
    | '/products/nyaynetra'
    | '/products/shunyai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplicationsRoute: typeof ApplicationsRoute
  BlogRoute: typeof BlogRoute
  CognitesRoute: typeof CognitesRouteWithChildren
  ContactRoute: typeof ContactRoute
  DevelopersRoute: typeof DevelopersRoute
  EnterpriseRoute: typeof EnterpriseRoute
  PilotsRoute: typeof PilotsRoute
  PlatformRoute: typeof PlatformRoute
  PricingRoute: typeof PricingRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ResearchRoute: typeof ResearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilots': {
      id: '/pilots'
      path: '/pilots'
      fullPath: '/pilots'
      preLoaderRoute: typeof PilotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cognites': {
      id: '/cognites'
      path: '/cognites'
      fullPath: '/cognites'
      preLoaderRoute: typeof CognitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/shunyai': {
      id: '/products/shunyai'
      path: '/shunyai'
      fullPath: '/products/shunyai'
      preLoaderRoute: typeof ProductsShunyaiRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/nyaynetra': {
      id: '/products/nyaynetra'
      path: '/nyaynetra'
      fullPath: '/products/nyaynetra'
      preLoaderRoute: typeof ProductsNyaynetraRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/ikshana': {
      id: '/products/ikshana'
      path: '/ikshana'
      fullPath: '/products/ikshana'
      preLoaderRoute: typeof ProductsIkshanaRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/health-hub': {
      id: '/products/health-hub'
      path: '/health-hub'
      fullPath: '/products/health-hub'
      preLoaderRoute: typeof ProductsHealthHubRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/externovate': {
      id: '/products/externovate'
      path: '/externovate'
      fullPath: '/products/externovate'
      preLoaderRoute: typeof ProductsExternovateRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/cwos': {
      id: '/products/cwos'
      path: '/cwos'
      fullPath: '/products/cwos'
      preLoaderRoute: typeof ProductsCwosRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/cogni-doc': {
      id: '/products/cogni-doc'
      path: '/cogni-doc'
      fullPath: '/products/cogni-doc'
      preLoaderRoute: typeof ProductsCogniDocRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/cobots': {
      id: '/products/cobots'
      path: '/cobots'
      fullPath: '/products/cobots'
      preLoaderRoute: typeof ProductsCobotsRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/chaxu': {
      id: '/products/chaxu'
      path: '/chaxu'
      fullPath: '/products/chaxu'
      preLoaderRoute: typeof ProductsChaxuRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/blisstrail': {
      id: '/products/blisstrail'
      path: '/blisstrail'
      fullPath: '/products/blisstrail'
      preLoaderRoute: typeof ProductsBlisstrailRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/awcs': {
      id: '/products/awcs'
      path: '/awcs'
      fullPath: '/products/awcs'
      preLoaderRoute: typeof ProductsAwcsRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/askcogni': {
      id: '/products/askcogni'
      path: '/askcogni'
      fullPath: '/products/askcogni'
      preLoaderRoute: typeof ProductsAskcogniRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/cognites/mycogni': {
      id: '/cognites/mycogni'
      path: '/mycogni'
      fullPath: '/cognites/mycogni'
      preLoaderRoute: typeof CognitesMycogniRouteImport
      parentRoute: typeof CognitesRoute
    }
    '/cognites/login': {
      id: '/cognites/login'
      path: '/login'
      fullPath: '/cognites/login'
      preLoaderRoute: typeof CognitesLoginRouteImport
      parentRoute: typeof CognitesRoute
    }
  }
}

interface CognitesRouteChildren {
  CognitesLoginRoute: typeof CognitesLoginRoute
  CognitesMycogniRoute: typeof CognitesMycogniRoute
}

const CognitesRouteChildren: CognitesRouteChildren = {
  CognitesLoginRoute: CognitesLoginRoute,
  CognitesMycogniRoute: CognitesMycogniRoute,
}

const CognitesRouteWithChildren = CognitesRoute._addFileChildren(
  CognitesRouteChildren,
)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsAskcogniRoute: typeof ProductsAskcogniRoute
  ProductsAwcsRoute: typeof ProductsAwcsRoute
  ProductsBlisstrailRoute: typeof ProductsBlisstrailRoute
  ProductsChaxuRoute: typeof ProductsChaxuRoute
  ProductsCobotsRoute: typeof ProductsCobotsRoute
  ProductsCogniDocRoute: typeof ProductsCogniDocRoute
  ProductsCwosRoute: typeof ProductsCwosRoute
  ProductsExternovateRoute: typeof ProductsExternovateRoute
  ProductsHealthHubRoute: typeof ProductsHealthHubRoute
  ProductsIkshanaRoute: typeof ProductsIkshanaRoute
  ProductsNyaynetraRoute: typeof ProductsNyaynetraRoute
  ProductsShunyaiRoute: typeof ProductsShunyaiRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsAskcogniRoute: ProductsAskcogniRoute,
  ProductsAwcsRoute: ProductsAwcsRoute,
  ProductsBlisstrailRoute: ProductsBlisstrailRoute,
  ProductsChaxuRoute: ProductsChaxuRoute,
  ProductsCobotsRoute: ProductsCobotsRoute,
  ProductsCogniDocRoute: ProductsCogniDocRoute,
  ProductsCwosRoute: ProductsCwosRoute,
  ProductsExternovateRoute: ProductsExternovateRoute,
  ProductsHealthHubRoute: ProductsHealthHubRoute,
  ProductsIkshanaRoute: ProductsIkshanaRoute,
  ProductsNyaynetraRoute: ProductsNyaynetraRoute,
  ProductsShunyaiRoute: ProductsShunyaiRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplicationsRoute: ApplicationsRoute,
  BlogRoute: BlogRoute,
  CognitesRoute: CognitesRouteWithChildren,
  ContactRoute: ContactRoute,
  DevelopersRoute: DevelopersRoute,
  EnterpriseRoute: EnterpriseRoute,
  PilotsRoute: PilotsRoute,
  PlatformRoute: PlatformRoute,
  PricingRoute: PricingRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ResearchRoute: ResearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
